import { Product } from '@/types';

export const CATEGORIES = [
  'Sarees', 'Lehengas', 'Kurtis', 'Dupattas',
  'Festive Sets', 'Accessories', 'Frock',
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: '1', slug: 'banarasi-silk-saree',
    name: 'Banarasi Silk Saree', category: 'Sarees',
    description: 'A luxurious Banarasi silk saree with intricate gold zari work. Perfect for weddings and festive occasions. Hand-woven by master artisans of Varanasi.',
    images: ['https://images.unsplash.com/photo-1610030469983-98e550d6193c?q=80&w=600&auto=format&fit=crop'],
    price: 12500, originalPrice: 15000, discountPercent: 17,
    sizes: ['Free Size'],
    colors: [{ name: 'Gold', hex: '#D4AF37' }, { name: 'Red', hex: '#CC0000' }],
    stock: 15, rating: 4.8, reviewCount: 120, isFeatured: true, isNewArrival: true,
  },
  {
    id: '2', slug: 'royal-bridal-lehenga',
    name: 'Royal Bridal Lehenga', category: 'Lehengas',
    description: 'An exquisite bridal lehenga crafted with heavy embroidery and mirror work. A royal ensemble for your most special day.',
    images: ['https://images.unsplash.com/photo-1617627143233-5e61f94ed29c?q=80&w=600&auto=format&fit=crop'],
    price: 45000, originalPrice: 50000, discountPercent: 10,
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: [{ name: 'Crimson', hex: '#DC143C' }, { name: 'Navy', hex: '#001F5B' }],
    stock: 8, rating: 4.9, reviewCount: 87, isFeatured: true, isNewArrival: true,
  },
  {
    id: '3', slug: 'anarkali-festive-set',
    name: 'Anarkali Festive Set', category: 'Festive Sets',
    description: 'Flowing Anarkali with delicate thread work and a matching dupatta. The epitome of festive elegance.',
    images: ['https://images.unsplash.com/photo-1583391733956-6c78276477e2?q=80&w=600&auto=format&fit=crop'],
    price: 8750, originalPrice: 8750, discountPercent: 0,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: [{ name: 'Rose', hex: '#FF007F' }],
    stock: 22, rating: 4.6, reviewCount: 54, isFeatured: false, isNewArrival: false,
  },
  {
    id: '4', slug: 'chanderi-silk-kurti',
    name: 'Chanderi Silk Kurti', category: 'Kurtis',
    description: 'Lightweight Chanderi silk kurti with hand-block printing. Effortlessly elegant for everyday royalty.',
    images: ['https://images.unsplash.com/photo-1585487000160-6ebcfceb0d03?q=80&w=600&auto=format&fit=crop'],
    price: 3200, originalPrice: 3200, discountPercent: 0,
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: [{ name: 'Ivory', hex: '#FFFFF0' }, { name: 'Teal', hex: '#008080' }],
    stock: 30, rating: 4.4, reviewCount: 39, isFeatured: false, isNewArrival: true,
  },
  {
    id: '5', slug: 'phulkari-embroidered-dupatta',
    name: 'Phulkari Embroidered Dupatta', category: 'Dupattas',
    description: 'A stunning dupatta with intricate Phulkari embroidery from Punjab, adding a royal touch to any ensemble.',
    images: ['https://images.unsplash.com/photo-1594938298603-c8148c4b1ad4?q=80&w=600&auto=format&fit=crop'],
    price: 2100, originalPrice: 2500, discountPercent: 16,
    sizes: ['Free Size'],
    colors: [{ name: 'Multicolor', hex: '#FF69B4' }],
    stock: 40, rating: 4.7, reviewCount: 63, isFeatured: false, isNewArrival: false,
  },
  {
    id: '6', slug: 'kundan-jewellery-set',
    name: 'Kundan Jewellery Set', category: 'Accessories',
    description: 'Handcrafted Kundan necklace with matching earrings. Inspired by Mughal-era jewellery traditions.',
    images: ['https://images.unsplash.com/photo-1535632787350-4e68ef0ac584?q=80&w=600&auto=format&fit=crop'],
    price: 6800, originalPrice: 6800, discountPercent: 0,
    sizes: ['Free Size'],
    colors: [{ name: 'Gold', hex: '#D4AF37' }],
    stock: 12, rating: 4.5, reviewCount: 31, isFeatured: true, isNewArrival: true,
  },
  {
    id: '7', slug: 'georgette-sequence-saree',
    name: 'Georgette Sequence Saree', category: 'Sarees',
    description: 'Lightweight georgette saree with sequence border. Perfect for cocktail parties and evening events.',
    images: ['https://images.unsplash.com/photo-1617196034183-421b4040ed20?q=80&w=600&auto=format&fit=crop'],
    price: 7500, originalPrice: 7500, discountPercent: 0,
    sizes: ['Free Size'],
    colors: [{ name: 'Black', hex: '#000000' }, { name: 'Maroon', hex: '#800000' }],
    stock: 18, rating: 4.3, reviewCount: 47, isFeatured: false, isNewArrival: false,
  },
  {
    id: '8', slug: 'velvet-lehenga-set',
    name: 'Velvet Lehenga Set', category: 'Lehengas',
    description: 'Rich velvet lehenga with gold embossing and a contrast dupatta. A statement piece for winter festivities.',
    images: ['https://images.unsplash.com/photo-1580914901432-0c3d5a41bfef?q=80&w=600&auto=format&fit=crop'],
    price: 28000, originalPrice: 29500, discountPercent: 5,
    sizes: ['XS', 'S', 'M', 'L'],
    colors: [{ name: 'Royal Blue', hex: '#4169E1' }, { name: 'Burgundy', hex: '#800020' }],
    stock: 6, rating: 4.9, reviewCount: 22, isFeatured: true, isNewArrival: true,
  },
  {
    id: '9', slug: 'rosette-floral-midi-frock-1',
    name: 'Rosette Floral Midi Frock', category: 'Frock',
    description: 'Brighten your wardrobe with this elegant yellow floral midi dress. Featuring a soft V-neckline, puff sleeves, and a flowy tiered silhouette.',
    images: ['https://res.cloudinary.com/douvhybil/image/upload/v1772311857/AWP%20Shopping-products/izyxmmy0wuzmwgpc5vfb.jpg'],
    price: 750, originalPrice: 1000, discountPercent: 25,
    sizes: ['S', 'M', 'L', 'XL', 'XXL', '3XL', '4XL', '5XL', '6XL'],
    colors: [{ name: 'Yellow', hex: '#F5C518' }],
    stock: 35, rating: 4.5, reviewCount: 70, isFeatured: false, isNewArrival: false,
  },
  {
    id: '10', slug: 'cotton-palazzo-set',
    name: 'Cotton Palazzo Set', category: 'Festive Sets',
    description: 'Breezy cotton palazzo set with tie-dye pattern. The ideal festive-casual look for summer gatherings.',
    images: ['https://images.unsplash.com/photo-1591154669695-5f2a8d20c089?q=80&w=600&auto=format&fit=crop'],
    price: 2800, originalPrice: 2800, discountPercent: 0,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: [{ name: 'Sky Blue', hex: '#87CEEB' }, { name: 'Peach', hex: '#FFCBA4' }],
    stock: 35, rating: 4.2, reviewCount: 28, isFeatured: false, isNewArrival: false,
  },
  {
    id: '11', slug: 'zardozi-embroidered-kurti',
    name: 'Zardozi Embroidered Kurti', category: 'Kurtis',
    description: 'Elegant Zardozi embroidered kurti in pure cotton. A royal design for formal festive wear.',
    images: ['https://images.unsplash.com/photo-1603344797033-f0f4f587ab60?q=80&w=600&auto=format&fit=crop'],
    price: 4500, originalPrice: 5600, discountPercent: 20,
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: [{ name: 'Emerald', hex: '#50C878' }, { name: 'Purple', hex: '#5A2D82' }],
    stock: 14, rating: 4.6, reviewCount: 41, isFeatured: false, isNewArrival: false,
  },
  {
    id: '12', slug: 'embellished-potli-bag',
    name: 'Embellished Potli Bag', category: 'Accessories',
    description: 'Handcrafted potli bag with mirror work and golden tassels. The perfect ethnic evening clutch.',
    images: ['https://images.unsplash.com/photo-1548036328-c9fa89d128fa?q=80&w=600&auto=format&fit=crop'],
    price: 1800, originalPrice: 1800, discountPercent: 0,
    sizes: ['Free Size'],
    colors: [{ name: 'Gold', hex: '#D4AF37' }, { name: 'Pink', hex: '#FFC0CB' }],
    stock: 25, rating: 4.4, reviewCount: 33, isFeatured: false, isNewArrival: true,
  },
];
